export const formElementsData = {
  name: "testing for git rebase",
  email: "test@gmail.com",
  propertyName: "test",
  regNo: "12345678",
  ownerName: "test",
  isOwner: "Tidak (No)",
  informantsRelationship: "test",
  nameOfReportingCompany: "test",
  reportingCompanyWebsite: "test.com",
  reportingCompanyAddress: "test",
  propertyOwerEmail: "test@gmail.com",
  informantsPhoneNo: "134567853",
  productLink: "test.com",
  productDetails: "test 1 2 3 4 5 6 7 8 9 10",
  proofOfDirectSelling: "FormSubmission/dummyData/dummyImage.png",
  proofOfPowerOfAttorneyFile: "FormSubmission/dummyData/dummyImage.png",
  proofOfPropertyFile: "FormSubmission/dummyData/dummyImage.png",
  moreProductsListFile: "FormSubmission/dummyData/dummyImage.png",
};
